version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sonarr_server_1
      APP_PORT: 8989
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/sonarr:develop-version-4.0.4.1695@sha256:165a5e5d923b4c51618208f9d05a6285b745ef51a5e45c81ee981e4f4fde3311
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
